// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525225923_Fase5RelatosAtendimento")]
    partial class Fase5RelatosAtendimento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AtividadeHabilidade", b =>
                {
                    b.Property<int>("AtividadeId")
                        .HasColumnType("integer");

                    b.Property<int>("HabilidadeId")
                        .HasColumnType("integer");

                    b.HasKey("AtividadeId", "HabilidadeId");

                    b.HasIndex("HabilidadeId");

                    b.ToTable("AtividadeHabilidade", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrencystamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalizedname");

                    b.HasKey("Id")
                        .HasName("pk_aspnetroles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("rolenameindex");

                    b.ToTable("aspnetroles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claimtype");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claimvalue");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("roleid");

                    b.HasKey("Id")
                        .HasName("pk_aspnetroleclaims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_aspnetroleclaims_roleid");

                    b.ToTable("aspnetroleclaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claimtype");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claimvalue");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("pk_aspnetuserclaims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_aspnetuserclaims_userid");

                    b.ToTable("aspnetuserclaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("loginprovider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("providerkey");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("providerdisplayname");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userid");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_aspnetuserlogins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_aspnetuserlogins_userid");

                    b.ToTable("aspnetuserlogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("userid");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("roleid");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_aspnetuserroles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_aspnetuserroles_roleid");

                    b.ToTable("aspnetuserroles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("userid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("loginprovider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_aspnetusertokens");

                    b.ToTable("aspnetusertokens", (string)null);
                });

            modelBuilder.Entity("api.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ano")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ano");

                    b.Property<string>("Bairro")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("complemento");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("datanascimento");

                    b.Property<string>("DiasSemanaAtendimentoJson")
                        .HasColumnType("text")
                        .HasColumnName("diassemanaatendimentojson");

                    b.Property<int?>("DuracaoAtendimentoMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("duracaoatendimentominutos");

                    b.Property<string>("Estado")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("estado");

                    b.Property<int?>("FrequenciaSemanalAtendimento")
                        .HasColumnType("integer")
                        .HasColumnName("frequenciasemanalatendimento");

                    b.Property<int>("IdEscola")
                        .HasColumnType("integer")
                        .HasColumnName("idescola");

                    b.Property<int>("IdProfessor")
                        .HasColumnType("integer")
                        .HasColumnName("idprofessor");

                    b.Property<int?>("IdResponsavel")
                        .HasColumnType("integer")
                        .HasColumnName("idresponsavel");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("logradouro");

                    b.Property<string>("NivelEnsino")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nivelensino");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("nomecompleto");

                    b.Property<int?>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<string>("PerfilPedagogicoNecessidades")
                        .HasColumnType("text")
                        .HasColumnName("perfilpedagogiconecessidades");

                    b.Property<string>("PerfilPedagogicoPotencialidades")
                        .HasColumnType("text")
                        .HasColumnName("perfilpedagogicopotencialidades");

                    b.Property<string>("Sexo")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("sexo");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<int?>("TipoAtendimentoAee")
                        .HasColumnType("integer")
                        .HasColumnName("tipoatendimentoaee");

                    b.Property<string>("Turno")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("turno");

                    b.HasKey("Id")
                        .HasName("pk_alunos");

                    b.HasIndex("IdEscola")
                        .HasDatabaseName("ix_alunos_idescola");

                    b.HasIndex("IdProfessor")
                        .HasDatabaseName("ix_alunos_idprofessor");

                    b.HasIndex("IdResponsavel")
                        .HasDatabaseName("ix_alunos_idresponsavel");

                    b.ToTable("alunos");
                });

            modelBuilder.Entity("api.Models.AlunosXPlanejamento", b =>
                {
                    b.Property<int>("PlanejamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("planejamentoid")
                        .HasColumnOrder(1);

                    b.Property<int>("AlunoId")
                        .HasColumnType("integer")
                        .HasColumnName("alunoid")
                        .HasColumnOrder(0);

                    b.HasKey("PlanejamentoId", "AlunoId");

                    b.HasIndex("AlunoId");

                    b.ToTable("alunosxplanejamento");
                });

            modelBuilder.Entity("api.Models.Atividade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<int>("BlocoId")
                        .HasColumnType("integer")
                        .HasColumnName("blocoid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Enunciado")
                        .HasColumnType("text")
                        .HasColumnName("enunciado");

                    b.Property<string>("EtapaMax")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("etapamax");

                    b.Property<string>("EtapaMin")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("etapamin");

                    b.Property<string>("ImagemUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("imagemurl");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nivel");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("titulo");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_atividade");

                    b.HasIndex("BlocoId")
                        .HasDatabaseName("ix_atividade_blocoid");

                    b.ToTable("atividade");
                });

            modelBuilder.Entity("api.Models.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Resumo")
                        .HasColumnType("text")
                        .HasColumnName("resumo");

                    b.HasKey("Id")
                        .HasName("pk_avaliacao");

                    b.ToTable("avaliacao");
                });

            modelBuilder.Entity("api.Models.AvaliacaoAluno", b =>
                {
                    b.Property<int>("AvaliacaoDiagnosticaId")
                        .HasColumnType("integer")
                        .HasColumnName("avaliacaodiagnosticaid");

                    b.Property<int>("AlunoId")
                        .HasColumnType("integer")
                        .HasColumnName("alunoid");

                    b.Property<DateTime?>("DataConclusaoRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataconclusaoregistro");

                    b.Property<string>("ObservacaoGeral")
                        .HasColumnType("text")
                        .HasColumnName("observacaogeral");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("AvaliacaoDiagnosticaId", "AlunoId");

                    b.HasIndex("AlunoId")
                        .HasDatabaseName("ix_avaliacoes_alunos_alunoid");

                    b.ToTable("avaliacoes_alunos");
                });

            modelBuilder.Entity("api.Models.AvaliacaoDiagnostica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Concluida")
                        .HasColumnType("boolean")
                        .HasColumnName("concluida");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<DateTime>("DataAplicacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataaplicacao");

                    b.Property<int?>("EscolaId")
                        .HasColumnType("integer")
                        .HasColumnName("escolaid");

                    b.Property<string>("Objetivo")
                        .HasColumnType("text")
                        .HasColumnName("objetivo");

                    b.Property<int?>("ProfessorId")
                        .HasColumnType("integer")
                        .HasColumnName("professorid");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("titulo");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_avaliacoes_diagnosticas");

                    b.HasIndex("EscolaId")
                        .HasDatabaseName("ix_avaliacoes_diagnosticas_escolaid");

                    b.HasIndex("ProfessorId")
                        .HasDatabaseName("ix_avaliacoes_diagnosticas_professorid");

                    b.ToTable("avaliacoes_diagnosticas");
                });

            modelBuilder.Entity("api.Models.AvaliacaoDiagnosticaAtividade", b =>
                {
                    b.Property<int>("AvaliacaoDiagnosticaId")
                        .HasColumnType("integer")
                        .HasColumnName("avaliacaodiagnosticaid");

                    b.Property<int>("AtividadeId")
                        .HasColumnType("integer")
                        .HasColumnName("atividadeid");

                    b.HasKey("AvaliacaoDiagnosticaId", "AtividadeId");

                    b.HasIndex("AtividadeId")
                        .HasDatabaseName("ix_avaliacoes_diagnosticas_atividades_atividadeid");

                    b.ToTable("avaliacoes_diagnosticas_atividades");
                });

            modelBuilder.Entity("api.Models.AvaliacaoDiagnosticaBloco", b =>
                {
                    b.Property<int>("AvaliacaoDiagnosticaId")
                        .HasColumnType("integer")
                        .HasColumnName("avaliacaodiagnosticaid");

                    b.Property<int>("BlocoId")
                        .HasColumnType("integer")
                        .HasColumnName("blocoid");

                    b.Property<int>("OrdemApresentacao")
                        .HasColumnType("integer")
                        .HasColumnName("ordemapresentacao");

                    b.HasKey("AvaliacaoDiagnosticaId", "BlocoId");

                    b.HasIndex("BlocoId")
                        .HasDatabaseName("ix_avaliacoes_diagnosticas_blocos_blocoid");

                    b.ToTable("avaliacoes_diagnosticas_blocos");
                });

            modelBuilder.Entity("api.Models.AvaliacaoXPlanejamento", b =>
                {
                    b.Property<int>("PlanejamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("planejamentoid")
                        .HasColumnOrder(1);

                    b.Property<int>("AvaliacaoId")
                        .HasColumnType("integer")
                        .HasColumnName("avaliacaoid")
                        .HasColumnOrder(0);

                    b.HasKey("PlanejamentoId", "AvaliacaoId");

                    b.HasIndex("AvaliacaoId");

                    b.ToTable("avaliacaoxplanejamento");
                });

            modelBuilder.Entity("api.Models.Bloco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Icone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icone");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacao");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("status");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("titulo");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_bloco");

                    b.ToTable("bloco");
                });

            modelBuilder.Entity("api.Models.DesempenhoAtividade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("integer")
                        .HasColumnName("alunoid");

                    b.Property<int>("AtividadeId")
                        .HasColumnType("integer")
                        .HasColumnName("atividadeid");

                    b.Property<int>("AvaliacaoDiagnosticaId")
                        .HasColumnType("integer")
                        .HasColumnName("avaliacaodiagnosticaid");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataregistro");

                    b.Property<string>("NivelRealizacao")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nivelrealizacao");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.HasKey("Id")
                        .HasName("pk_desempenhos_atividades");

                    b.HasIndex("AlunoId")
                        .HasDatabaseName("ix_desempenhos_atividades_alunoid");

                    b.HasIndex("AtividadeId")
                        .HasDatabaseName("ix_desempenhos_atividades_atividadeid");

                    b.HasIndex("AvaliacaoDiagnosticaId", "DataRegistro");

                    b.HasIndex("AvaliacaoDiagnosticaId", "AlunoId", "AtividadeId");

                    b.ToTable("desempenhos_atividades");
                });

            modelBuilder.Entity("api.Models.DiagnosticoFinal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("integer")
                        .HasColumnName("alunoid");

                    b.Property<int>("AvaliacaoDiagnosticaId")
                        .HasColumnType("integer")
                        .HasColumnName("avaliacaodiagnosticaid");

                    b.Property<DateTime>("GeradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("geradoem");

                    b.Property<string>("NivelPerfilAutonomia")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("nivelperfilautonomia");

                    b.Property<string>("Recomendacoes")
                        .HasColumnType("text")
                        .HasColumnName("recomendacoes");

                    b.Property<string>("Resumo")
                        .HasColumnType("text")
                        .HasColumnName("resumo");

                    b.HasKey("Id")
                        .HasName("pk_diagnosticos_finais");

                    b.HasIndex("AlunoId")
                        .HasDatabaseName("ix_diagnosticos_finais_alunoid");

                    b.HasIndex("AvaliacaoDiagnosticaId")
                        .HasDatabaseName("ix_diagnosticos_finais_avaliacaodiagnosticaid");

                    b.ToTable("diagnosticos_finais");
                });

            modelBuilder.Entity("api.Models.Escola", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Bairro")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("complemento");

                    b.Property<string>("Estado")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("estado");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("logradouro");

                    b.Property<string>("NomeInstituicao")
                        .HasColumnType("text")
                        .HasColumnName("nomeinstituicao");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<string>("Tipo")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("tipo");

                    b.HasKey("ID")
                        .HasName("pk_escolas");

                    b.ToTable("escolas");
                });

            modelBuilder.Entity("api.Models.EscolaXProfessor", b =>
                {
                    b.Property<int>("EscolaId")
                        .HasColumnType("integer")
                        .HasColumnName("escolaid")
                        .HasColumnOrder(0);

                    b.Property<int>("ProfessorId")
                        .HasColumnType("integer")
                        .HasColumnName("professorid")
                        .HasColumnOrder(1);

                    b.HasKey("EscolaId", "ProfessorId")
                        .HasName("pk_escolasxprofessores");

                    b.HasIndex("ProfessorId")
                        .HasDatabaseName("ix_escolasxprofessores_professorid");

                    b.ToTable("escolasxprofessores");
                });

            modelBuilder.Entity("api.Models.Estrategias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.HasKey("Id")
                        .HasName("pk_estrategias");

                    b.ToTable("estrategias");
                });

            modelBuilder.Entity("api.Models.EstrategiasXPlanejamento", b =>
                {
                    b.Property<int>("PlanejamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("planejamentoid")
                        .HasColumnOrder(1);

                    b.Property<int>("EstrategiaId")
                        .HasColumnType("integer")
                        .HasColumnName("estrategiaid")
                        .HasColumnOrder(0);

                    b.HasKey("PlanejamentoId", "EstrategiaId");

                    b.HasIndex("EstrategiaId");

                    b.ToTable("estrategiasxplanejamento");
                });

            modelBuilder.Entity("api.Models.EstudoDeCaso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("integer")
                        .HasColumnName("alunoid");

                    b.Property<string>("ContextoSituacao")
                        .HasColumnType("text")
                        .HasColumnName("contextosituacao");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("integer")
                        .HasColumnName("professorid");

                    b.Property<string>("TextoSimulado")
                        .HasColumnType("text")
                        .HasColumnName("textosimulado");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_estudos_caso");

                    b.HasIndex("AlunoId")
                        .HasDatabaseName("ix_estudos_caso_alunoid");

                    b.HasIndex("ProfessorId")
                        .HasDatabaseName("ix_estudos_caso_professorid");

                    b.ToTable("estudos_caso");
                });

            modelBuilder.Entity("api.Models.EstudoDeCasoEixoCatalogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("DescricaoHint")
                        .HasColumnType("text")
                        .HasColumnName("descricaohint");

                    b.Property<int>("OrdemExibicao")
                        .HasColumnType("integer")
                        .HasColumnName("ordemexibicao");

                    b.Property<string>("Rotulo")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("rotulo");

                    b.HasKey("Id")
                        .HasName("pk_estudo_caso_eixos_catalogo");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("estudo_caso_eixos_catalogo");
                });

            modelBuilder.Entity("api.Models.EstudoDeCasoItemEixo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Anotacao")
                        .HasColumnType("text")
                        .HasColumnName("anotacao");

                    b.Property<int>("EixoCatalogoId")
                        .HasColumnType("integer")
                        .HasColumnName("eixocatalogoid");

                    b.Property<int>("EstudoDeCasoId")
                        .HasColumnType("integer")
                        .HasColumnName("estudodecasoid");

                    b.HasKey("Id")
                        .HasName("pk_estudo_caso_itens_eixo");

                    b.HasIndex("EixoCatalogoId")
                        .HasDatabaseName("ix_estudo_caso_itens_eixo_eixocatalogoid");

                    b.HasIndex("EstudoDeCasoId", "EixoCatalogoId")
                        .IsUnique();

                    b.ToTable("estudo_caso_itens_eixo");
                });

            modelBuilder.Entity("api.Models.Habilidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<int>("IdNivelEnsino")
                        .HasColumnType("integer")
                        .HasColumnName("idnivelensino");

                    b.Property<string>("Resumo")
                        .HasColumnType("text")
                        .HasColumnName("resumo");

                    b.Property<string>("Tipo")
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_habilidades");

                    b.ToTable("habilidades");
                });

            modelBuilder.Entity("api.Models.HabilidadesXPlanejamento", b =>
                {
                    b.Property<int>("PlanejamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("planejamentoid")
                        .HasColumnOrder(1);

                    b.Property<int>("HabilidadeId")
                        .HasColumnType("integer")
                        .HasColumnName("habilidadeid")
                        .HasColumnOrder(0);

                    b.HasKey("PlanejamentoId", "HabilidadeId");

                    b.HasIndex("HabilidadeId");

                    b.ToTable("habilidadesxplanejamento");
                });

            modelBuilder.Entity("api.Models.Laudo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoCid")
                        .HasColumnType("text")
                        .HasColumnName("codigocid");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("descricao");

                    b.Property<int>("IdAluno")
                        .HasColumnType("integer")
                        .HasColumnName("idaluno");

                    b.Property<string>("NomeMedico")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("nomemedico");

                    b.HasKey("Id")
                        .HasName("pk_laudos");

                    b.HasIndex("IdAluno")
                        .HasDatabaseName("ix_laudos_idaluno");

                    b.ToTable("laudos");
                });

            modelBuilder.Entity("api.Models.ObservacaoAlunoAvaliacaoHistorico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("integer")
                        .HasColumnName("alunoid");

                    b.Property<int>("AvaliacaoDiagnosticaId")
                        .HasColumnType("integer")
                        .HasColumnName("avaliacaodiagnosticaid");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataregistro");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.HasKey("Id")
                        .HasName("pk_observacoes_alunos_avaliacao_historico");

                    b.HasIndex("AvaliacaoDiagnosticaId", "AlunoId", "DataRegistro");

                    b.ToTable("observacoes_alunos_avaliacao_historico");
                });

            modelBuilder.Entity("api.Models.Planejamento", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Apelido")
                        .HasColumnType("text")
                        .HasColumnName("apelido");

                    b.Property<string>("AssinaturaCargo")
                        .HasColumnType("text")
                        .HasColumnName("assinaturacargo");

                    b.Property<string>("AssinaturaNomeResponsavel")
                        .HasColumnType("text")
                        .HasColumnName("assinaturanomeresponsavel");

                    b.Property<DateOnly>("DataFim")
                        .HasColumnType("date")
                        .HasColumnName("datafim");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("datainicio");

                    b.Property<string>("DescicaoPlanejamento")
                        .HasColumnType("text")
                        .HasColumnName("descicaoplanejamento");

                    b.Property<bool>("DocumentoDeclaradoAssinado")
                        .HasColumnType("boolean")
                        .HasColumnName("documentodeclaradoassinado");

                    b.Property<int>("IdProfessor")
                        .HasColumnType("integer")
                        .HasColumnName("idprofessor");

                    b.Property<string>("ObjetivoCurtoPrazo")
                        .HasColumnType("text")
                        .HasColumnName("objetivocurtoprazo");

                    b.Property<string>("ObjetivoLongoPrazo")
                        .HasColumnType("text")
                        .HasColumnName("objetivolongoprazo");

                    b.Property<string>("ObjetivoMedioPrazo")
                        .HasColumnType("text")
                        .HasColumnName("objetivomedioprazo");

                    b.HasKey("ID")
                        .HasName("pk_planejamentos");

                    b.HasIndex("IdProfessor")
                        .HasDatabaseName("ix_planejamentos_idprofessor");

                    b.ToTable("planejamentos");
                });

            modelBuilder.Entity("api.Models.PlanejamentoEncontro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataEnc")
                        .HasColumnType("date")
                        .HasColumnName("dataenc");

                    b.Property<int?>("EstrategiaId")
                        .HasColumnType("integer")
                        .HasColumnName("estrategiaid");

                    b.Property<int?>("HabilidadeId")
                        .HasColumnType("integer")
                        .HasColumnName("habilidadeid");

                    b.Property<int>("PlanejamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("planejamentoid");

                    b.Property<string>("TextoPlanejado")
                        .HasColumnType("text")
                        .HasColumnName("textoplanejado");

                    b.Property<string>("TextoRealizado")
                        .HasColumnType("text")
                        .HasColumnName("textorealizado");

                    b.HasKey("Id")
                        .HasName("pk_planejamento_encontros");

                    b.HasIndex("EstrategiaId")
                        .HasDatabaseName("ix_planejamento_encontros_estrategiaid");

                    b.HasIndex("HabilidadeId")
                        .HasDatabaseName("ix_planejamento_encontros_habilidadeid");

                    b.HasIndex("PlanejamentoId", "DataEnc")
                        .HasDatabaseName("ix_planejamento_encontros_planejamentoid_dataenc");

                    b.ToTable("planejamento_encontros");
                });

            modelBuilder.Entity("api.Models.Professor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Bairro")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("complemento");

                    b.Property<string>("Disciplinas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("disciplinas");

                    b.Property<string>("Estado")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("estado");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("bytea")
                        .HasColumnName("foto");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("logradouro");

                    b.Property<string>("NivelEnsino")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nivelensino");

                    b.Property<string>("NomeCompleto")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("nomecompleto");

                    b.Property<int?>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<string>("Sexo")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("sexo");

                    b.Property<string>("Sobre")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("sobre");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.HasKey("ID")
                        .HasName("pk_professores");

                    b.ToTable("professores");
                });

            modelBuilder.Entity("api.Models.RelatoAtendimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("integer")
                        .HasColumnName("alunoid");

                    b.Property<string>("AvancosJson")
                        .HasColumnType("text")
                        .HasColumnName("avancosjson");

                    b.Property<DateOnly>("DataSessao")
                        .HasColumnType("date")
                        .HasColumnName("datasessao");

                    b.Property<string>("DificuldadesJson")
                        .HasColumnType("text")
                        .HasColumnName("dificuldadesjson");

                    b.Property<int?>("EstrategiaId")
                        .HasColumnType("integer")
                        .HasColumnName("estrategiaid");

                    b.Property<int?>("HabilidadeId")
                        .HasColumnType("integer")
                        .HasColumnName("habilidadeid");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<int?>("PlanejamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("planejamentoid");

                    b.Property<bool>("PresencaPresente")
                        .HasColumnType("boolean")
                        .HasColumnName("presencapresente");

                    b.Property<int>("TipoOcorrencia")
                        .HasColumnType("integer")
                        .HasColumnName("tipoocorrencia");

                    b.HasKey("Id")
                        .HasName("pk_relatos_atendimento");

                    b.HasIndex("EstrategiaId")
                        .HasDatabaseName("ix_relatos_atendimento_estrategiaid");

                    b.HasIndex("HabilidadeId")
                        .HasDatabaseName("ix_relatos_atendimento_habilidadeid");

                    b.HasIndex("PlanejamentoId")
                        .HasDatabaseName("ix_relatos_atendimento_planejamentoid");

                    b.HasIndex("AlunoId", "DataSessao")
                        .HasDatabaseName("ix_relatos_atendimento_alunoid_datasessao");

                    b.ToTable("relatos_atendimento");
                });

            modelBuilder.Entity("api.Models.Responsavel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("complemento");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("estado");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("logradouro");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nomecompleto");

                    b.Property<int?>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("pk_responsaveis");

                    b.ToTable("responsaveis");
                });

            modelBuilder.Entity("api.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("accessfailedcount");

                    b.Property<bool>("AceitouTermos")
                        .HasColumnType("boolean")
                        .HasColumnName("aceitoutermos");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrencystamp");

                    b.Property<bool>("DeveAlterarSenha")
                        .HasColumnType("boolean")
                        .HasColumnName("devealterarsenha");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("emailconfirmed");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expirationdate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<bool>("IsEmbaixadora")
                        .HasColumnType("boolean")
                        .HasColumnName("isembaixadora");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockoutenabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockoutend");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalizedemail");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalizedusername");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phonenumber");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phonenumberconfirmed");

                    b.Property<int?>("ProfessorId")
                        .HasColumnType("integer")
                        .HasColumnName("professorid");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("securitystamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("twofactorenabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_aspnetusers");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("emailindex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("usernameindex");

                    b.HasIndex("ProfessorId")
                        .IsUnique()
                        .HasDatabaseName("ix_aspnetusers_professorid");

                    b.ToTable("aspnetusers", (string)null);
                });

            modelBuilder.Entity("AtividadeHabilidade", b =>
                {
                    b.HasOne("api.Models.Atividade", null)
                        .WithMany()
                        .HasForeignKey("AtividadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_atividadehabilidade_atividade_atividadesid");

                    b.HasOne("api.Models.Habilidade", null)
                        .WithMany()
                        .HasForeignKey("HabilidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_atividadehabilidade_habilidades_habilidadesid");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aspnetroleclaims_aspnetroles_roleid");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("api.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aspnetuserclaims_aspnetusers_userid");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("api.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aspnetuserlogins_aspnetusers_userid");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aspnetuserroles_aspnetroles_roleid");

                    b.HasOne("api.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aspnetuserroles_aspnetusers_userid");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("api.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aspnetusertokens_aspnetusers_userid");
                });

            modelBuilder.Entity("api.Models.Aluno", b =>
                {
                    b.HasOne("api.Models.Escola", "Escola")
                        .WithMany()
                        .HasForeignKey("IdEscola")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alunos_escolas_idescola");

                    b.HasOne("api.Models.Professor", "Professor")
                        .WithMany()
                        .HasForeignKey("IdProfessor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alunos_professores_idprofessor");

                    b.HasOne("api.Models.Responsavel", "Responsavel")
                        .WithMany("Alunos")
                        .HasForeignKey("IdResponsavel")
                        .HasConstraintName("fk_alunos_responsaveis_idresponsavel");

                    b.Navigation("Escola");

                    b.Navigation("Professor");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("api.Models.AlunosXPlanejamento", b =>
                {
                    b.HasOne("api.Models.Aluno", "Aluno")
                        .WithMany("AlunosXPlanejamentos")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alunosxplanejamento_alunos_alunoid");

                    b.HasOne("api.Models.Planejamento", "Planejamento")
                        .WithMany("AlunosXPlanejamentos")
                        .HasForeignKey("PlanejamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alunosxplanejamento_planejamentos_planejamentoid");

                    b.Navigation("Aluno");

                    b.Navigation("Planejamento");
                });

            modelBuilder.Entity("api.Models.Atividade", b =>
                {
                    b.HasOne("api.Models.Bloco", "Bloco")
                        .WithMany("Atividades")
                        .HasForeignKey("BlocoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_atividade_bloco_blocoid");

                    b.Navigation("Bloco");
                });

            modelBuilder.Entity("api.Models.AvaliacaoAluno", b =>
                {
                    b.HasOne("api.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_avaliacoes_alunos_alunos_alunoid");

                    b.HasOne("api.Models.AvaliacaoDiagnostica", "AvaliacaoDiagnostica")
                        .WithMany("AlunosParticipantes")
                        .HasForeignKey("AvaliacaoDiagnosticaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_avaliacoes_alunos_avaliacoes_diagnosticas_avaliacaodiagnost~");

                    b.Navigation("Aluno");

                    b.Navigation("AvaliacaoDiagnostica");
                });

            modelBuilder.Entity("api.Models.AvaliacaoDiagnostica", b =>
                {
                    b.HasOne("api.Models.Escola", "Escola")
                        .WithMany()
                        .HasForeignKey("EscolaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_avaliacoes_diagnosticas_escolas_escolaid");

                    b.HasOne("api.Models.Professor", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .HasConstraintName("fk_avaliacoes_diagnosticas_professores_professorid");

                    b.Navigation("Escola");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("api.Models.AvaliacaoDiagnosticaAtividade", b =>
                {
                    b.HasOne("api.Models.Atividade", "Atividade")
                        .WithMany()
                        .HasForeignKey("AtividadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_avaliacoes_diagnosticas_atividades_atividade_atividadeid");

                    b.HasOne("api.Models.AvaliacaoDiagnostica", "AvaliacaoDiagnostica")
                        .WithMany("AtividadesSelecionadas")
                        .HasForeignKey("AvaliacaoDiagnosticaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_avaliacoes_diagnosticas_atividades_avaliacoes_diagnosticas_~");

                    b.Navigation("Atividade");

                    b.Navigation("AvaliacaoDiagnostica");
                });

            modelBuilder.Entity("api.Models.AvaliacaoDiagnosticaBloco", b =>
                {
                    b.HasOne("api.Models.AvaliacaoDiagnostica", "AvaliacaoDiagnostica")
                        .WithMany("BlocosSelecionados")
                        .HasForeignKey("AvaliacaoDiagnosticaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_avaliacoes_diagnosticas_blocos_avaliacoes_diagnosticas_aval~");

                    b.HasOne("api.Models.Bloco", "Bloco")
                        .WithMany()
                        .HasForeignKey("BlocoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_avaliacoes_diagnosticas_blocos_bloco_blocoid");

                    b.Navigation("AvaliacaoDiagnostica");

                    b.Navigation("Bloco");
                });

            modelBuilder.Entity("api.Models.AvaliacaoXPlanejamento", b =>
                {
                    b.HasOne("api.Models.Avaliacao", "Avaliacao")
                        .WithMany("AvaliacaoXPlanejamento")
                        .HasForeignKey("AvaliacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_avaliacaoxplanejamento_avaliacao_avaliacaoid");

                    b.HasOne("api.Models.Planejamento", "Planejamento")
                        .WithMany("AvaliacaoXPlanejamentos")
                        .HasForeignKey("PlanejamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_avaliacaoxplanejamento_planejamentos_planejamentoid");

                    b.Navigation("Avaliacao");

                    b.Navigation("Planejamento");
                });

            modelBuilder.Entity("api.Models.DesempenhoAtividade", b =>
                {
                    b.HasOne("api.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_desempenhos_atividades_alunos_alunoid");

                    b.HasOne("api.Models.Atividade", "Atividade")
                        .WithMany()
                        .HasForeignKey("AtividadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_desempenhos_atividades_atividade_atividadeid");

                    b.HasOne("api.Models.AvaliacaoDiagnostica", "AvaliacaoDiagnostica")
                        .WithMany("RegistrosDesempenho")
                        .HasForeignKey("AvaliacaoDiagnosticaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_desempenhos_atividades_avaliacoes_diagnosticas_avaliacaodia~");

                    b.Navigation("Aluno");

                    b.Navigation("Atividade");

                    b.Navigation("AvaliacaoDiagnostica");
                });

            modelBuilder.Entity("api.Models.DiagnosticoFinal", b =>
                {
                    b.HasOne("api.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_diagnosticos_finais_alunos_alunoid");

                    b.HasOne("api.Models.AvaliacaoDiagnostica", "AvaliacaoDiagnostica")
                        .WithMany()
                        .HasForeignKey("AvaliacaoDiagnosticaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_diagnosticos_finais_avaliacoes_diagnosticas_avaliacaodiagno~");

                    b.Navigation("Aluno");

                    b.Navigation("AvaliacaoDiagnostica");
                });

            modelBuilder.Entity("api.Models.EscolaXProfessor", b =>
                {
                    b.HasOne("api.Models.Escola", "Escola")
                        .WithMany("EscolaXProfessores")
                        .HasForeignKey("EscolaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_escolasxprofessores_escolas_escolaid");

                    b.HasOne("api.Models.Professor", "Professor")
                        .WithMany("EscolaXProfessores")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_escolasxprofessores_professores_professorid");

                    b.Navigation("Escola");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("api.Models.EstrategiasXPlanejamento", b =>
                {
                    b.HasOne("api.Models.Estrategias", "Estrategia")
                        .WithMany("EstrategiasXPlanejamentos")
                        .HasForeignKey("EstrategiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_estrategiasxplanejamento_estrategias_estrategiaid");

                    b.HasOne("api.Models.Planejamento", "Planejamento")
                        .WithMany("EstrategiasXPlanejamentos")
                        .HasForeignKey("PlanejamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_estrategiasxplanejamento_planejamentos_planejamentoid");

                    b.Navigation("Estrategia");

                    b.Navigation("Planejamento");
                });

            modelBuilder.Entity("api.Models.EstudoDeCaso", b =>
                {
                    b.HasOne("api.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_estudos_caso_alunos_alunoid");

                    b.HasOne("api.Models.Professor", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_estudos_caso_professores_professorid");

                    b.Navigation("Aluno");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("api.Models.EstudoDeCasoItemEixo", b =>
                {
                    b.HasOne("api.Models.EstudoDeCasoEixoCatalogo", "CatalogoEixo")
                        .WithMany("Itens")
                        .HasForeignKey("EixoCatalogoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_estudo_caso_itens_eixo_estudo_caso_eixos_catalogo_eixocatal~");

                    b.HasOne("api.Models.EstudoDeCaso", "EstudoDeCaso")
                        .WithMany("ItensEixo")
                        .HasForeignKey("EstudoDeCasoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_estudo_caso_itens_eixo_estudos_caso_estudodecasoid");

                    b.Navigation("CatalogoEixo");

                    b.Navigation("EstudoDeCaso");
                });

            modelBuilder.Entity("api.Models.HabilidadesXPlanejamento", b =>
                {
                    b.HasOne("api.Models.Habilidade", "Habilidade")
                        .WithMany("HabilidadesXPlanejamentos")
                        .HasForeignKey("HabilidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_habilidadesxplanejamento_habilidades_habilidadeid");

                    b.HasOne("api.Models.Planejamento", "Planejamento")
                        .WithMany("HabilidadesXPlanejamentos")
                        .HasForeignKey("PlanejamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_habilidadesxplanejamento_planejamentos_planejamentoid");

                    b.Navigation("Habilidade");

                    b.Navigation("Planejamento");
                });

            modelBuilder.Entity("api.Models.Laudo", b =>
                {
                    b.HasOne("api.Models.Aluno", "Aluno")
                        .WithMany("Laudos")
                        .HasForeignKey("IdAluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_laudos_alunos_idaluno");

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("api.Models.Planejamento", b =>
                {
                    b.HasOne("api.Models.Professor", "Professor")
                        .WithMany("Planejamentos")
                        .HasForeignKey("IdProfessor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_planejamentos_professores_idprofessor");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("api.Models.PlanejamentoEncontro", b =>
                {
                    b.HasOne("api.Models.Estrategias", "Estrategia")
                        .WithMany()
                        .HasForeignKey("EstrategiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_planejamento_encontros_estrategias_estrategiaid");

                    b.HasOne("api.Models.Habilidade", "Habilidade")
                        .WithMany()
                        .HasForeignKey("HabilidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_planejamento_encontros_habilidades_habilidadeid");

                    b.HasOne("api.Models.Planejamento", "Planejamento")
                        .WithMany("Encontros")
                        .HasForeignKey("PlanejamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_planejamento_encontros_planejamentos_planejamentoid");

                    b.Navigation("Estrategia");

                    b.Navigation("Habilidade");

                    b.Navigation("Planejamento");
                });

            modelBuilder.Entity("api.Models.RelatoAtendimento", b =>
                {
                    b.HasOne("api.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_relatos_atendimento_alunos_alunoid");

                    b.HasOne("api.Models.Estrategias", "Estrategia")
                        .WithMany()
                        .HasForeignKey("EstrategiaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_relatos_atendimento_estrategias_estrategiaid");

                    b.HasOne("api.Models.Habilidade", "Habilidade")
                        .WithMany()
                        .HasForeignKey("HabilidadeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_relatos_atendimento_habilidades_habilidadeid");

                    b.HasOne("api.Models.Planejamento", "Planejamento")
                        .WithMany()
                        .HasForeignKey("PlanejamentoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_relatos_atendimento_planejamentos_planejamentoid");

                    b.Navigation("Aluno");

                    b.Navigation("Estrategia");

                    b.Navigation("Habilidade");

                    b.Navigation("Planejamento");
                });

            modelBuilder.Entity("api.Models.Usuario", b =>
                {
                    b.HasOne("api.Models.Professor", "Professor")
                        .WithOne("Usuario")
                        .HasForeignKey("api.Models.Usuario", "ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_aspnetusers_professores_professorid");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("api.Models.Aluno", b =>
                {
                    b.Navigation("AlunosXPlanejamentos");

                    b.Navigation("Laudos");
                });

            modelBuilder.Entity("api.Models.Avaliacao", b =>
                {
                    b.Navigation("AvaliacaoXPlanejamento");
                });

            modelBuilder.Entity("api.Models.AvaliacaoDiagnostica", b =>
                {
                    b.Navigation("AlunosParticipantes");

                    b.Navigation("AtividadesSelecionadas");

                    b.Navigation("BlocosSelecionados");

                    b.Navigation("RegistrosDesempenho");
                });

            modelBuilder.Entity("api.Models.Bloco", b =>
                {
                    b.Navigation("Atividades");
                });

            modelBuilder.Entity("api.Models.Escola", b =>
                {
                    b.Navigation("EscolaXProfessores");
                });

            modelBuilder.Entity("api.Models.Estrategias", b =>
                {
                    b.Navigation("EstrategiasXPlanejamentos");
                });

            modelBuilder.Entity("api.Models.EstudoDeCaso", b =>
                {
                    b.Navigation("ItensEixo");
                });

            modelBuilder.Entity("api.Models.EstudoDeCasoEixoCatalogo", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("api.Models.Habilidade", b =>
                {
                    b.Navigation("HabilidadesXPlanejamentos");
                });

            modelBuilder.Entity("api.Models.Planejamento", b =>
                {
                    b.Navigation("AlunosXPlanejamentos");

                    b.Navigation("AvaliacaoXPlanejamentos");

                    b.Navigation("Encontros");

                    b.Navigation("EstrategiasXPlanejamentos");

                    b.Navigation("HabilidadesXPlanejamentos");
                });

            modelBuilder.Entity("api.Models.Professor", b =>
                {
                    b.Navigation("EscolaXProfessores");

                    b.Navigation("Planejamentos");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("api.Models.Responsavel", b =>
                {
                    b.Navigation("Alunos");
                });
#pragma warning restore 612, 618
        }
    }
}
