name: Build, publish and deploy to MonsterASP.NET - Development

on: 
  push:
    branches: [ staging ]

jobs:
  build_and_deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0  # ajuste para sua versão (ex: 8.0.x ou 9.0.x)

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish --runtime win-x86  # ou win-x64 se preferir

    - name: Deploy to MonsterASP.NET via WebDeploy
      uses: rasmusbuchholdt/simply-web-deploy@2.1.0
      with:
        website-name: ${{ secrets.WEBSITE_NAME_DEVELOPMENT }}
        server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME_DEVELOPMENT }}
        server-username: ${{ secrets.SERVER_USERNAME_DEVELOPMENT }}
        server-password: ${{ secrets.SERVER_PASSWORD_DEVELOPMENT }}
